### ISSUE TITLE
不能绑定原生属性

### ISSUE THREAD

**Issue by Alvin-Liu** [leezng/el-form-renderer#10]
> version: "1.0.2"

## 举个例子

content如下：
    
    content: [
      {
        $type: 'input',
        $id: 'name',
        label: '活动名称',
        $el: {
          placeholder: '请选择',
          size: 'mini'
        }
      }
    ]

`el-input`可以正常渲染，`size`生效，`placeholder`没有生效

## 原因

`placeholder`不是`el-input`的`props`属性，`size`是，在`render-from-item.js`的`renderFormItemContent`中：

    return h('el-' + elType, {
      props: props,
      on: {
        // 手动更新表单数据
        input: (value) => {
          this.$emit('updateValue', { id: data.$id, value })
        }
      }
    },...

只处理了`props`，没有处理`attrs`，`placeholder`属于`el-input`的`attrs`，其他属性同

## 其他

一个很尴尬的问题是，属于`props`还是`attrs`直接看element-UI文档有些是很难区分的，期待解决一下

**Comment by leezng** [comment]
感谢反馈，#11 采用写入attrs解决，目前尚无更好的方法
