### ISSUE TITLE
el-form-renderer.js丢失

### ISSUE THREAD

**Issue by levy9527** [leezng/el-form-renderer#12]
npm上el-form-renderer@1.0.3这个包，下载后发现，丢失el-form-renderer.js，因为package.json里main定义的是这个文件，结果导致
```js
import ElFormRenderer from 'el-form-renderer'
```
报错
`Cannot find module 'el-form-renderer’`

**Comment by levy9527** [comment]
是不是没有build就发包了。。。

**Comment by leezng** [comment]
fixed in 1.0.5
