### ISSUE TITLE
npm包中有node_modules包含了element-ui

### ISSUE THREAD

**Issue by levy9527** [leezng/el-form-renderer#14]
查看node_modules下的el-form-renderer，发现包内也有一个node_modules文件夹，放着element-ui的依赖，这个可以去掉的吧。。。

**Comment by leezng** [comment]
并没有
![image](https://user-images.githubusercontent.com/13777294/40919479-2a60424a-683c-11e8-8cd8-bb94122296ff.png)

**Comment by levy9527** [comment]
好，我知道了，是因为指定的依赖为1.x版本，yarn的时候另行安装了一个
