### ISSUE TITLE
Avoid mutating a prop directly...

### ISSUE THREAD

**Issue by adin234** [leezng/el-form-renderer#23]
```
found in
---> <RenderFormItem>
       <ElForm>
         <ElFormRenderer>
           <MyComponent> at src/path/to/my/Component.vue
             <Root>
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "value"
```

Upon inspection, it seems like this is the line affecting [this](https://github.com/leezng/el-form-renderer/blob/dev/src/index.js#L21) because the error went away when i did [this](https://gist.github.com/adin234/c4ac56ac867164dd6fb64312db96d104#file-fukenvue-js-L45) but of course the form stopped working afterwards

#Sample
https://github.com/adin234/el-form-renderer-warning

**Comment by leezng** [comment]
@adin234 Add an example please

**Comment by adin234** [comment]
https://github.com/adin234/el-form-renderer-warning

**Comment by FerrielMelarpis** [comment]
I believe this is related to this issue vuejs/vue-test-utils#532

**Comment by leezng** [comment]
After I ran the code, I found no warning in this example. Do you have the missing code? Or provide more detailed information.
![image](https://user-images.githubusercontent.com/13777294/42800018-9f80d6d2-89cc-11e8-8399-3b252a4881ff.png)

**Comment by adin234** [comment]
it happens in the test, i think @FerrielMelarpis i right, it is related to the issue he linked.
