### ISSUE TITLE
表单默认值问题

### ISSUE THREAD

**Issue by MrTreasure** [leezng/el-form-renderer#6]
某个缓存策略导致设置默认值有问题。
具体表现为：
```javascript
        // 设置默认值
        let defaultValue
        if (this.isEdit) {
          defaultValue = node[item.mapperName] ? node[item.mapperName] : ''
        } else {
          defaultValue = ''
        }
        // 设着通用属性
        const formItem = {
          $id: item.mapperName,
          $type: 'input',
          $default: defaultValue,
          label: item.descName,
          $el: {
            disabled: !this.setAttr(item, 1)
          },
          rules: [{
            required: item.isRequired === '01', message: '请填写该字段', trigger: 'blur'
          }]
        }
```
打开一个包含动态表单的对话框，第一次设置一个默认值以后，修改默认值属性，第二次打开仍然为第一次的值。此时defaultValue已经改变，页面并没有发生明显变化

目前采用的解决办法：
```html
<el-form-renderer v-if="orgDialog" :content="formContent" inline label-width="120px" ref="orgForm"></el-form-renderer>
```
```javascript
this.$refs.orgForm.resetFields()
```
为组件添加vif指令，每次生成formContent的时候调用resetFields方法

**Comment by leezng** [comment]
但你创建一个表单时，表单是没有任何值的，所以会将默认值写入表单，根据双向绑定，这时候你可以通过 `getFormValue` 获取到表单的值，相当于默认值已经变成了真实的表单值，当你下一次传入一个新的默认值时，此时表单已经存在值了，不会再用默认值去覆盖已存在的表单值，相当于我不能去修改用户在输入框已经填入的值。

**Comment by houjiazong** [comment]
@MrTreasure 如果是异步更新default value（比如通过请求API获取数据，然后显示在表单上），可以将content作为compute

![image](https://user-images.githubusercontent.com/1658546/39859356-2ee1613e-546c-11e8-84e6-c06b8a6ed341.png)

**Comment by MrTreasure** [comment]
@leezng 但是这个需求是真实存在的。因为一个表单需要涉及到不同用户的修改，每一次修改都应该设置不同的值
@houjiazong 我不太喜欢在computed进行复杂的计算，而且这一个fields中间还涉及到不同的类型转换。把逻辑都揉进这里，会使得计算属性特别复杂

**Comment by levy9527** [comment]
@MrTreasure 使用updateValue({id: '', value:''}) 可以解决该问题。我有写PR建议在文档上标明此方法，但作者没有Merge，可能其理念不认同吧
